import Link from "next/link";
import { Icon } from "@/components/ui/icons";
import { legacy } from "@/components/ui/legacy";
import { PageHeader, Price, StatCard, StatusBadge } from "@/components/ui/primitives";
import { chartData, products, sales } from "@/lib/mock-data";

export default function DashboardPage() {
  return <div>
    <PageHeader eyebrow="ថ្ងៃពុធ ទី០៨ ខែតុលា ឆ្នាំ២០២៦" title="អរុណសួស្តី ម៉ាលីស" description="នេះជាទិដ្ឋភាពសកម្មភាពរបស់ហាងអ្នកនៅថ្ងៃនេះ។" action={<button className={`${legacy.button} ${legacy.buttonSecondary}`}><Icon name="calendar" size={15} />ថ្ងៃនេះ <Icon name="chevron-down" size={13} /></button>} />
    <div className={legacy.statGrid}><StatCard label="ការលក់ថ្ងៃនេះ" value="$12,450.80" change="12.8%" icon="receipt" /><StatCard label="ប្រតិបត្តិការ" value="284" change="8.4%" icon="shopping-bag" tone="green" /><StatCard label="ប្រាក់ចំណេញសរុប" value="$4,820.40" change="6.2%" icon="chart" tone="blue" /><StatCard label="ទំនិញស្តុកជិតអស់" value="12" change="-3.1%" icon="alert" tone="amber" /></div>
    <div className={legacy.dashboardGrid}>
      <div className={legacy.panel}><div className={legacy.panelHeader}><div><h2>ទិដ្ឋភាពការលក់</h2><p>លទ្ធផលចំណូលក្នុងរយៈពេល ១២ ខែចុងក្រោយ</p></div><div className={legacy.periodTabs}><button className="bg-[#e1f3ec] font-semibold text-[#057450]">១២ ខែ</button><button>៣០ ថ្ងៃ</button><button>៧ ថ្ងៃ</button></div></div><div className={legacy.panelBody}><div className={legacy.chartWrap}><div className={legacy.chartGrid}><span /><span /><span /><span /><span /></div><div className={legacy.chartBars}>{chartData.map((height, index) => <span key={index} className={legacy.chartBar} style={{ height: `${height / 1.3}%` }} />)}</div><div className={legacy.chartLabels}><span>វិច្ឆិកា</span><span>មករា</span><span>មីនា</span><span>ឧសភា</span><span>កក្កដា</span><span>កញ្ញា</span><span>តុលា</span></div></div><div className="flex gap-[13px] text-[12px] text-[#858e9d]"><span><i className="mr-1 inline-block h-[7px] w-[7px] rounded-full bg-[#07885f]" />ការលក់សរុប</span><span><i className="mr-1 inline-block h-[7px] w-[7px] rounded-full bg-[#d5eee5]" />ឆ្នាំមុន</span></div></div></div>
      <div className={legacy.panel}><div className={legacy.panelHeader}><div><h2>ផលិតផលលក់ដាច់</h2><p>តាមចំណូលក្នុងខែនេះ</p></div><button className={legacy.actionButton} aria-label="សកម្មភាពបន្ថែម"><Icon name="more" /></button></div><div className={legacy.panelBody}>{products.slice(0, 5).map((product, index) => <div className={legacy.topProduct} key={product.id}><span className={legacy.rank}>០{index + 1}</span><img className={legacy.productThumb} src={product.imageUrl} alt="" /><span><strong>{product.name}</strong><small>{[428, 316, 284, 198, 164][index]} ឯកតា</small></span><b><Price value={[1240, 976, 852, 642, 488][index]} /></b></div>)}</div></div>
      <div className={legacy.panel}><div className={legacy.panelHeader}><div><h2>ប្រតិបត្តិការថ្មីៗ</h2><p>សកម្មភាពថ្មីបំផុតពីបញ្ជីលក់របស់អ្នក</p></div><Link className={legacy.textLink} href="/sales">មើលទាំងអស់ <Icon name="chevron-right" size={13} /></Link></div><div className={legacy.panelBody}><table className={legacy.miniTable}><thead><tr><th>វិក្កយបត្រ</th><th>អតិថិជន</th><th>ការទូទាត់</th><th className="text-right">សរុប</th></tr></thead><tbody>{sales.slice(0, 5).map((sale) => <tr key={sale.id}><td><strong>{sale.invoice}</strong><small>{sale.date.split(" · ")[1]}</small></td><td>{sale.customer}</td><td><StatusBadge status={sale.payment} /></td><td className="text-right"><strong><Price value={sale.total} /></strong></td></tr>)}</tbody></table></div></div>
      <div className={legacy.panel}><div className={legacy.panelHeader}><div><h2>ត្រូវការយកចិត្តទុកដាក់</h2><p>ផលិតផលដែលនៅក្រោមកម្រិតស្តុកអប្បបរមា</p></div><Link className={legacy.textLink} href="/inventory">មើលស្តុក <Icon name="chevron-right" size={13} /></Link></div><div className={legacy.panelBody}>{products.filter((product) => product.stock <= product.minimumStock).slice(0, 4).map((product) => <div className="flex items-center gap-[9px] border-b border-[#f0f2f5] py-2.5 last:border-0" key={product.id}><img className={legacy.productThumb} src={product.imageUrl} alt="" /><span className="flex-1"><strong className="block text-[13px]">{product.name}</strong><small className="text-[12px] text-[#9ba3ad]">អប្បបរមា {product.minimumStock} {product.unit}</small></span><span className="text-[13px] font-bold text-[#c3414b]">{product.stock}</span><span className="h-[3px] w-[34px] rounded bg-[#f4dddd]"><i className="block h-full rounded bg-[#d66a71]" style={{ width: `${Math.max(8, product.stock / product.minimumStock * 100)}%` }} /></span></div>)}</div></div>
    </div>
  </div>;
}
