"use client";
import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/ui/icons";
import { Button, PageHeader } from "@/components/ui/primitives";

export default function NewProductPage() {
  const [saved, setSaved] = useState(false);
  return <div><PageHeader eyebrow="ទំនិញ / ផលិតផល" title="បន្ថែមផលិតផល" description="បង្កើតផលិតផលថ្មីសម្រាប់បញ្ជីទំនិញរបស់ហាង។" action={<Link href="/products" className="button button-secondary"><Icon name="chevron-left" size={15} />ត្រឡប់ទៅផលិតផល</Link>} /><form className="form-layout" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><div className="form-card"><section className="form-section"><h2>ព័ត៌មានមូលដ្ឋាន</h2><p>បញ្ចូលព័ត៌មានដើម្បីឲ្យបុគ្គលិកស្វែងរកផលិតផលបានឆាប់រហ័សនៅពេលលក់។</p><div className="form-grid"><div className="form-field"><label htmlFor="name">ឈ្មោះផលិតផល</label><input id="name" required placeholder="ឧ. កូកា-កូឡា ៣៣០មល" /></div><div className="form-field"><label htmlFor="sku">លេខកូដ SKU</label><input id="sku" required placeholder="ឧ. BEV-001" /></div><div className="form-field"><label htmlFor="barcode">បាកូដ</label><input id="barcode" placeholder="ស្កេន ឬបញ្ចូលបាកូដ" /></div><div className="form-field"><label htmlFor="category">ប្រភេទផលិតផល</label><select id="category" defaultValue="ភេសជ្ជៈ"><option>ភេសជ្ជៈ</option><option>អាហារសម្រន់</option><option>គ្រឿងទេស</option><option>សម្ភារៈថែទាំខ្លួន</option></select></div><div className="form-field"><label htmlFor="unit">ឯកតា</label><select id="unit" defaultValue="ដុំ"><option>ដុំ</option><option>កំប៉ុង</option><option>ដប</option><option>កញ្ចប់</option><option>ប្រអប់</option></select></div></div></section><section className="form-section"><h2>តម្លៃ និងស្តុក</h2><p>កំណត់តម្លៃលក់ និងកម្រិតជូនដំណឹងអំពីស្តុក។</p><div className="form-grid"><div className="form-field"><label htmlFor="cost">តម្លៃដើម</label><input id="cost" required type="number" step="0.01" min="0" placeholder="0.00" /></div><div className="form-field"><label htmlFor="selling">តម្លៃលក់</label><input id="selling" required type="number" step="0.01" min="0" placeholder="0.00" /></div><div className="form-field"><label htmlFor="initial">ស្តុកដំបូង</label><input id="initial" required type="number" min="0" placeholder="0" /></div><div className="form-field"><label htmlFor="minimum">កម្រិតស្តុកអប្បបរមា</label><input id="minimum" required type="number" min="0" defaultValue="10" /></div></div></section><section className="form-section"><h2>រូបភាពផលិតផល</h2><p>ដាក់រូបភាពច្បាស់ ដើម្បីជួយអ្នកលក់សម្គាល់ផលិតផល។</p><div className="form-field"><label htmlFor="image">តំណភ្ជាប់រូបភាព</label><input id="image" type="url" placeholder="https://images.unsplash.com/..." /></div></section><section className="form-section"><div className="form-actions"><Link href="/products" className="button button-secondary">បោះបង់</Link><Button type="submit" icon="check">{saved ? "បានរក្សាទុក" : "រក្សាទុកផលិតផល"}</Button></div>{saved && <p className="save-message">បានបង្កើតផលិតផលដោយជោគជ័យ។ ផលិតផលនេះអាចបញ្ចូលស្តុកបាន។</p>}</section></div></form></div>;
}

